### ISSUE TITLE
PSI silently falls back to origin CrUX when there's no URL-level CrUX

### ISSUE THREAD

**Issue by jonchenn** [GoogleChromeLabs/AutoWebPerf#30]
When there's no enough traffic in CrUX for a specific URL, PSI falls back to origin-level CrUX data. As for now, the PSI gatherer couldn't tell the difference.

**Comment by jonchenn** [comment]
![image](https://user-images.githubusercontent.com/1644724/101023924-6ba42d00-3541-11eb-87a2-47d59c85cf17.png)

origin_fallback is populated only when the loadingExperience record has fallen back to showing origin data. In this example, if the loadingExperience record for https://www.samsung.com/in/smartphones/galaxy-note20/ has origin_fallback set to true, then it will have data for https://www.samsung.com/, not the full page.

**Comment by gilbertococchi** [comment]
This is the intended behaviour or PSI API also right now while using the CrUX API
