### ISSUE TITLE
"awp-config" example is not working

### ISSUE THREAD

**Issue by soobing** [GoogleChromeLabs/AutoWebPerf#35]
When excute command `./awp --help`
`./awp run --config=examples/awp-config.json` command shown in the below.

I think this is not workiing because of not giving mandatory arguments.

This example should be revised.

![image](https://user-images.githubusercontent.com/16860535/102452886-7fda4500-407e-11eb-8f34-1fe2e360da19.png)

**Comment by jonchenn** [comment]
Thanks for reporting this @soobing! I will fix this as soon as possible. Thanks!
