### ISSUE TITLE
Problem to get lighthouse score "works-offline"

### ISSUE THREAD

**Issue by krystianjj** [GoogleChromeLabs/AutoWebPerf#46]
Hi, 
When I run script I get some results but I have error
`[psi] Unable to assign json.lighthouseResult.audits["works-offline"].score to metrics: Cannot read property 'score' of undefined`
Has anyone have similar problem ?

**Comment by ptim** [comment]
I'm seeing this, too…

~~I wonder if this should instead be: `json.lighthouseResult.audits["service-worker"].score`?~~

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/service-worker.js

Edit: Scratch that - `json.lighthouseResult.audits["service-worker"].score` is separately defined:

https://github.com/GoogleChromeLabs/AutoWebPerf/blob/stable/src/gatherers/psi.js#L78-L79

and `works-offline` was removed on 2020-12-16: https://github.com/GoogleChrome/lighthouse/pull/11806
