### ISSUE TITLE
[webpagetest] invalid Location, pls try submitting your test again

### ISSUE THREAD

**Issue by iamlohith** [GoogleChromeLabs/AutoWebPerf#54]
I have try this command 
WPT_APIKEY=SAMPLE_KEY ./awp run examples/tests-wpt.json output/results.json
And i got this message webpagetest] invalid Location, pls try submitting your test again
So what needs to be done with this?

**Comment by jonchenn** [comment]
Will be fix in this PR: https://github.com/GoogleChromeLabs/AutoWebPerf/pull/68

**Comment by jonchenn** [comment]
Fixed with https://github.com/GoogleChromeLabs/AutoWebPerf/pull/68
