### ISSUE TITLE
Required env vars for WPT?

### ISSUE THREAD

**Issue by cweekly** [GoogleChromeLabs/AutoWebPerf#55]
I like the idea of this project, but am confused about how to start using it with my private instance of webpagetest.

The `docs/webpagetest.md` file notes:

```
## Required Environmental Variables

- `GCP_PROJECT_ID` - The project unique ID in the Google Cloud Platform. 
- `SERVICE_ACCOUNT_CREDENTIALS` - The path to the Service Account json file.
```  

... where I would've expected to see maybe optional env vars for WEBPAGETEST_SERVER or WPT_API_KEY or similar.
Is there really a dependency on GCP and a "Service Account json file"?

**Comment by jonchenn** [comment]
Hi @cweekly, sorry for late response here. 

If you are just auditing using WebPageTest, you don't need `GCP_PROJECT_ID` or `SERVICE_ACCOUNT_CREDENTIALS`, which is majorly used for PageSpeedIndex gatherer. However, if it's something prevent you running the audits, please let us know. We'd fix it. 

Thanks!

**Comment by jonchenn** [comment]
Closing this one as I assume the comment answered the question. However please feel free to reopen this issue as need. Thanks!
