### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by vitaliimelnychuk** [GoogleChromeLabs/AutoWebPerf#56]
Hello everyone! First of all, thank you for creating this framework, you have done amazing work!

I was trying to use the framework with different gatherers and it looks great for me so I started thinking about deploying it on the production to make it running regularly. 

Is this framework already exist on the NPM? It would be so great to be able to install it globally where I needed without cloning the repository itself. 

I am happy to help and create PR if it makes sense. 
@jonchenn

**Comment by jonchenn** [comment]
Hi @vitaliimelnychuk, apologize for the late reply here. That's an good idea. If you're still interested in creating an PR, please feel free to create one. 

Thanks so much for contributing to this project.

**Comment by jonchenn** [comment]
Hi @vitaliimelnychuk , please find the NPM package here: https://www.npmjs.com/package/autowebperf

Happy web-perfing!

**Comment by vitaliimelnychuk** [comment]
@jonchenn Hello! For some reason, I am getting 404 from the link you have posted. Is it publicly available?

**Comment by jonchenn** [comment]
Hi @vitaliimelnychuk, I unpublished the package since I submitted from the incorrect fork repo. I'll publish again after 24 hours. (as the policy of npmjs.org)

**Comment by jonchenn** [comment]
Hi @vitaliimelnychuk , the NPM package is published: https://www.npmjs.com/package/autowebperf

Thanks for the FR, closing this issue.
