### ISSUE TITLE
Error upon running tests

### ISSUE THREAD

**Issue by tymoey** [GoogleChromeLabs/AutoWebPerf#57]
While running the  sample test, I've gotten error below:

[ec2-user@ AutoWebPerf]$ ./awp run url:https://www.thinkwithgoogle.com/ json:output/results.json
Run with 1 test(s)
Run completed for 1 tests with errors:
[
  `[psi] Unable to assign json.lighthouseResult.audits["uses-webp-images"].details.overallSavingsBytes to metrics: Cannot read property 'details' of undefined`
]

Anything can be done?

**Comment by jonchenn** [comment]
It appears that there's some missing property in the specific audit result from the lighthouse. This needs to be fixed in the specific gather to prevent the missing property breaking the process.

I'll raise a PR to fix it.
