### ISSUE TITLE
Pass test URL from CLI without json file

### ISSUE THREAD

**Issue by elisameyer** [GoogleChromeLabs/AutoWebPerf#9]
It would be great to be able to run AWP from the CLI by just passing a single URL via the CLI like the [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci), rather than a JSON file. 

Ex. 

`./awp run url`

The test would be run with default values (mimicking the examples/tests.json file parameters)

**Comment by jonchenn** [comment]
This feature is included in previous commits. Use the following pattern to run with a single URL:

```
./awp run url:https://web.dev output/results.json
```
